### ISSUE TITLE
Database and ftb account bug

### ISSUE THREAD

**Issue by Qeyf** [usmannasir/beautiful_names#1]
When we install this package, we cannot create ftp account and database. When we delete this package, there is a bug in the panel. And it constantly opens the plug-ins page. Panel is unavailable. I would like you to check and correct it as soon as possible.

**Comment by HarikalarKutusu** [comment]
See the following for uninstall remedy:
https://forums.cyberpanel.net/discussion/4535/how-to-recover-from-beatifulnames-uninstall-bug/p1?new=1
